---
# file: roles/docker-gitlab/tasks/restore.yaml

# *****************************************************************************
# Setup the directory where the backup and restore is to take place

- name: restore dir
  file:
    state: directory
    path: '{{ gitlab_docker_restore_dir }}'
    owner: root
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
    recurse: no
    setype: svirt_sandbox_file_t

# *****************************************************************************
# Get data from tape

- name: find files
  files_in_dir:
    path: '{{ gitlab_docker_restore_dir }}'
  register: gitlab_backup

- name: data from tape
  bacula:
    command: restore
    storage: '{{ bacula_storage }}'
    fileset: '{{ bacula_fileset }}'
    dest: '{{ bacula_dest }}'
    path_to_restore: '{{ gitlab_docker_backup_dir }}'
  when: gitlab_backup.file_list == []

- name: find files
  files_in_dir:
    path: '{{ gitlab_docker_restore_dir }}'
  register: gitlab_backup

- name: File permissions
  file:
    path: '{{ gitlab_docker_restore_dir }}/{{ item }}'
    state: touch
    owner: root
    group: root
    mode: 'u=rwx,g=rwx,o='
  with_items: '{{ gitlab_backup.file_list | default([]) }}'

# *****************************************************************************
# restore the gitlap backup

- name: gitlab restore script
  command: '{{ docker_projects_dir }}/docker-gitlab/gitlab.sh restore'
  args:
    chdir: '{{ docker_restore_config_base_dir }}/{{ gitlab_dv_name }}/'
  when: gitlab_backup.file_list != []

# *****************************************************************************
# cleanup

- name: Remove files
  file:
    path: '{{ gitlab_docker_restore_dir }}'
    state: absent

- name: State file
  shell: 'date --rfc-3339=seconds > {{ docker_restore_config_base_dir }}/{{ gitlab_dv_name }}/restore.date.txt'
  when: st_gitlab_restore.stat.exists == False
